### ISSUE TITLE
Plse help me!

### ISSUE THREAD

**Issue by kel12345678** [fornwall/advent-of-code-2018-rs#1]
hello i have a sony xperia g3221 xa1 utra oreo=8 rooted with your tuto and l have termux but how install java without error for bind in tmux-bunch (post hax4us obsolete not valid because repo xeffyr have change) please my friend help me

**Comment by kel12345678** [comment]
sorry because its no the discution but i need help

**Comment by 0xXA** [comment]
Java currently is in disabled-packages in termux and moreover it eats battery.

**Comment by kel12345678** [comment]
hello tmux bunch need java for works it s possible to install openjdk but who do this

**Comment by kel12345678** [comment]
how bind payload in termux

**Comment by kel12345678** [comment]
hello i have one error in installation  tmuxbunch [dpkg: error: cannot access archive 'openjdk-9-jre-headless_9.2017.8.20-1_aarch64.deb': No such file or directory
rm: cannot remove 'openjdk-9-jre-headless_9.2017.8.20-1_aarch64.deb': No such file or directory]


 and error for bind[Using APK template: com.facebook.lite_123.0.0.9.97-133180350_minAPI14(armeabi-v7a)(nodpi)_apkmi.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20181209-27113-pesaoy/original/AndroidManifest.xml
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
Creating new keystore (using 'hax4us' as password and 'alias' as the key alias).
Exception in thread "main" java.io.FileNotFoundException: /data/data/com.termux/files/home/Tmux-Bunch/unsign/facebooklite1.apk: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:522)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:255)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:136)
        at net.fornwall.apksigner.zipio.ZipInput.<init>(ZipInput.java:20)]       plse hep me

xperia xa1 ultra aarch 64 api 26 oreo=8 rooted

**Comment by kel12345678** [comment]
help please
